### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by davider228** [mxcdevelop/mexc-api-sdk#35]
I installed [mexc-api-sdk](https://github.com/mxcdevelop/mexc-api-sdk)
pip install mexc_sdk-1.0.0-py3-none-any.whl
when i try run this :
from mexc_sdk import Spot
I got an error:
`Traceback (most recent call last):
  File "D:\all\Programming\arbitrage_screener_tg\exchanges_api.py", line 3, in <module>
    from mexc_sdk import Spot
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\mexc_sdk\__init__.py", line 502, in <module>
    from ._jsii import *
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\mexc_sdk\_jsii\__init__.py", line 11, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\providers\process.py", line 352, in load
    return self._process.send(request, LoadResponse)
           ^^^^^^^^^^^^^
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_utils.py", line 23, in wrapped
    stored.append(fgetter(self))
                  ^^^^^^^^^^^^^
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\providers\process.py", line 347, in _process
    process.start()
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\providers\process.py", line 260, in start
    self._process = subprocess.Popen(
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\dkala\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dkala\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Exception ignored in: <function _NodeProcess.__del__ at 0x000002BB5A3A9A80>
Traceback (most recent call last):
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\providers\process.py", line 228, in __del__
    self.stop()
  File "D:\all\Programming\arbitrage_screener_tg\venv\Lib\site-packages\jsii\_kernel\providers\process.py", line 291, in stop
    assert self._process.stdin is not None
           ^^^^^^^^^^^^^
AttributeError: '_NodeProcess' object has no attribute '_process'`

What I need to do to fix this?

**Comment by VinVag** [comment]
такая же ошибка -  не могу установить
